#!/usr/bin/env node
'use strict';
/**
 * setup.js — ติดตั้งและตั้งค่า mail-inet skill
 *
 * Usage:
 *   node setup.js
 */
const readline = require('readline');
const fs       = require('fs');
const path     = require('path');
const { execSync } = require('child_process');

const SKILL_DIR   = path.resolve(__dirname);
const CONFIG_DIR  = path.join(process.env.HOME, '.config', 'mail-inet');
const CONFIG_FILE = path.join(CONFIG_DIR, '.env');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

const ask    = (q)      => new Promise(r => rl.question(q, ans => r(ans)));
const askDef = (q, def) => ask(`${q} [${def}]: `).then(v => v.trim() || def);

// askPass ใช้ rl ตัวเดิม แต่ suppress echo ชั่วคราว
// วิธีนี้ป้องกัน stdin conflict ที่เกิดจากการใช้ raw mode แยก
const askPass = (q) => new Promise(r => {
  const orig = rl._writeToOutput.bind(rl);
  rl._writeToOutput = (s) => {
    // แสดงเฉพาะ newline ตอนกด Enter ซ่อนตัวอักษรที่พิมพ์
    if (s === '\r\n' || s === '\n' || s === '\r') rl.output.write('\n');
  };
  rl.question(q, (pass) => {
    rl._writeToOutput = orig; // คืน echo ปกติ
    r(pass);
  });
});

async function installDeps() {
  const nmPath = path.join(SKILL_DIR, 'node_modules');
  if (!fs.existsSync(nmPath)) {
    console.log('Installing dependencies...');
    execSync('npm install --production --silent', { cwd: SKILL_DIR, stdio: 'inherit' });
    console.log('  Done.\n');
  }
}

async function main() {
  console.log('================================');
  console.log('     mail-inet Skill Setup');
  console.log('================================\n');

  await installDeps();

  // ถ้ามี config แล้ว ถามก่อน
  if (fs.existsSync(CONFIG_FILE)) {
    console.log(`Config found at ${CONFIG_FILE}\n`);
    const choice = await askDef('Reconfigure? (yes/no)', 'no');
    if (!choice.startsWith('y')) { rl.close(); return; }
    console.log('');
  }

  // ── IMAP/SMTP ──────────────────────────────────────────────────────────────
  console.log('── Email (IMAP/SMTP) ──────────────────────────\n');

  console.log('IMAP Server:');
  const imapHost = await askDef('  Host', 'incoming.inet.co.th');
  const imapPort = await askDef('  Port', '993');
  const imapSsl  = await askDef('  Use SSL? (true/false)', 'true');

  console.log('\nSMTP Server:');
  const smtpHost = await askDef('  Host', 'outgoing.inet.co.th');
  const smtpPort = await askDef('  Port', '465');
  const smtpTls  = await askDef('  Use TLS? (true/false)', 'true');

  console.log('\nAccount:');
  const email    = await ask('  Email address: ');
  const password = await askPass('  Password: ');

  // ── CalDAV ─────────────────────────────────────────────────────────────────
  console.log('\n── Calendar (CalDAV) ──────────────────────────');
  console.log('(กด Enter เพื่อข้าม ถ้าไม่ต้องการใช้ calendar)\n');

  const caldavUrl = await ask('  CalDAV URL (เช่น https://caldav.example.com/dav/): ');
  let caldavUser = '', caldavPass = '';
  if (caldavUrl.trim()) {
    caldavUser = await ask('  CalDAV username: ');
    caldavPass = await askPass('  CalDAV password: ');
  }

  // ── บันทึก config ──────────────────────────────────────────────────────────
  fs.mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });

  const content = [
    `# mail-inet skill config`,
    `# Generated by setup.js — ${new Date().toISOString()}`,
    ``,
    `# IMAP (รับเมลล์)`,
    `IMAP_HOST=${imapHost}`,
    `IMAP_PORT=${imapPort}`,
    `IMAP_USER=${email.trim()}`,
    `IMAP_PASSWORD=${password}`,
    `IMAP_USE_SSL=${imapSsl}`,
    ``,
    `# SMTP (ส่งเมลล์)`,
    `SMTP_HOST=${smtpHost}`,
    `SMTP_PORT=${smtpPort}`,
    `SMTP_USER=${email.trim()}`,
    `SMTP_PASSWORD=${password}`,
    `SMTP_USE_TLS=${smtpTls}`,
    ``,
    `# CalDAV (ปฏิทิน)`,
    `CALDAV_URL=${caldavUrl.trim()}`,
    `CALDAV_USER=${caldavUser.trim()}`,
    `CALDAV_PASSWORD=${caldavPass}`,
  ].join('\n');

  fs.writeFileSync(CONFIG_FILE, content + '\n', { mode: 0o600 });
  console.log(`\nConfig saved to ${CONFIG_FILE}\n`);

  // ── ทดสอบการเชื่อมต่อ ──────────────────────────────────────────────────────
  console.log('Testing connections...\n');

  try {
    process.stdout.write('  IMAP... ');
    execSync(`node "${path.join(SKILL_DIR, 'scripts', 'list-folders.js')}"`, { stdio: 'pipe' });
    console.log('OK ✓');
  } catch {
    console.log('FAILED ✗ — ตรวจสอบ IMAP_HOST, IMAP_USER, IMAP_PASSWORD');
  }

  if (caldavUrl.trim()) {
    try {
      process.stdout.write('  CalDAV... ');
      execSync(`node "${path.join(SKILL_DIR, 'scripts', 'list-calendars.js')}"`, { stdio: 'pipe' });
      console.log('OK ✓');
    } catch {
      console.log('FAILED ✗ — ตรวจสอบ CALDAV_URL, CALDAV_USER, CALDAV_PASSWORD');
    }
  }

  console.log('\n================================');
  console.log('  Setup complete!');
  console.log('================================\n');
  console.log('Try:');
  console.log(`  node ${SKILL_DIR}/scripts/list-folders.js`);
  console.log(`  node ${SKILL_DIR}/scripts/list-emails.js --unread --limit 10`);
  if (caldavUrl.trim()) {
    console.log(`  node ${SKILL_DIR}/scripts/list-calendars.js`);
  }

  rl.close();
}

main().catch(err => {
  console.error('\nError:', err.message);
  rl.close();
  process.exit(1);
});
